spring.application.name=codecollab
server.port=8080
spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI}
jwt.secret=${JWT_SECRET}
cors.allowed-origins=https://code-forge-ai-omega.vercel.app/
jwt.expiration=86400000
groq.api.key=${GROQ_API_KEY}
spring.main.allow-circular-references=true